// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzxU2LOWfovyvFUPl64vGzS7RmNdJiElc',
    appId: '1:621305104990:web:f789f955b7577f364642cf',
    messagingSenderId: '621305104990',
    projectId: 'flash-chat-fa9ff',
    authDomain: 'flash-chat-fa9ff.firebaseapp.com',
    storageBucket: 'flash-chat-fa9ff.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDHltpDlg5OkXvJKqiPDOwbW2nIGy2Vweo',
    appId: '1:621305104990:android:10d1a8c0510bb3aa4642cf',
    messagingSenderId: '621305104990',
    projectId: 'flash-chat-fa9ff',
    storageBucket: 'flash-chat-fa9ff.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTTJiH5if-6JgTE1530zoptr42Ag3aVMQ',
    appId: '1:621305104990:ios:6f0fcfd1008eaa344642cf',
    messagingSenderId: '621305104990',
    projectId: 'flash-chat-fa9ff',
    storageBucket: 'flash-chat-fa9ff.appspot.com',
    iosClientId: '621305104990-59one2rip9p0hd06u18op88m32mrts8j.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBTTJiH5if-6JgTE1530zoptr42Ag3aVMQ',
    appId: '1:621305104990:ios:1de6437b05503ffb4642cf',
    messagingSenderId: '621305104990',
    projectId: 'flash-chat-fa9ff',
    storageBucket: 'flash-chat-fa9ff.appspot.com',
    iosClientId: '621305104990-ghcmcbg805hitk8rh4pj4um39r4db89r.apps.googleusercontent.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
